server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: dqwapi
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: \${DQWAPI_CLOUD_SQL_URL}
    username: \${DQWAPI_CLOUD_SQL_USERNAME}
    password: \${DQWAPI_CLOUD_SQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: \${DQWAPI_CLOUD_SQL_INSTANCE_CONNECTION_NAME}
        ipTypes: PUBLIC,PRIVATE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  swagger-ui:
    path: /api.html

dqwapi:
  version: $project.version
  path-prefix:
  kokoro-json: kokoro-new.json
  kokoro-flat-json: kokoro-flat.json
  response: 20

logging:
  level:
    com:
      google:
        cloud:
          sql:
            core:
              CoreSocketFactory: warn
