server:
  port: 8888

spring:
  application:
    name: dqwapi
  jackson:
    serialization:
      indent_output: true
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  swagger-ui:
    path: /api.html

dqwapi:
  version: $project.version
  kokoro-json: kokoro-new.json
  kokoro-flat-json: kokoro-flat.json
  response: 20
