server:
  port: 8888
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: dqwapi
  profiles:
    active: dwh-gcp-bigquery-dev #dwh-gcp-cloudsql-postgresql
  jackson:
    serialization:
      indent_output: true
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

springdoc:
  swagger-ui:
    path: /api.html

dqwapi:
  version: $project.version
  git-build-version: ${project.ext.gitProps['git.build.version']}
  git-commit-id: ${project.ext.gitProps['git.commit.id.abbrev']}
  fqdn: dqwapi.hirooka.pro
  path-prefix:
  kokoro-json: kokoro-v2.json
  kokoro-flat-json: kokoro-flat.json
  kokoro-persist: false
  response: 20
  run-on-cloud: \${RUN_ON_CLOUD:false}

gcp:
  project-id: hirooka-pro

logging:
  level:
    com:
      google:
        cloud:
          sql:
            core:
              CoreSocketFactory: warn

---
spring:
  config:
    activate:
      on-profile: dwh-gcp-bigquery-prod
gcp:
  run-on-cloud: \${RUN_ON_CLOUD:false}
  big-query:
    dataset: dqwapi
    table: kokoro
    table-type: CROSS
  cloud-storage:
    bucket: dqwapi
---
spring:
  config:
    activate:
      on-profile: dwh-gcp-bigquery-dev
gcp:
  run-on-cloud: \${RUN_ON_CLOUD:false}
  big-query:
    dataset: dqwapi
    table: kokoro-dev
    table-type: CROSS
  cloud-storage:
    bucket: dqwapi
---
spring:
  config:
    activate:
      on-profile: dwh-gcp-cloudsql-postgresql
  datasource:
    url: \${DQWAPI_CLOUD_SQL_POSTGRESQL_URL}
    username: \${DQWAPI_CLOUD_SQL_POSTGRESQL_USERNAME}
    password: \${DQWAPI_CLOUD_SQL_POSTGRESQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: \${DQWAPI_CLOUD_SQL_POSTGRESQL_INSTANCE_CONNECTION_NAME}
        ipTypes: PUBLIC,PRIVATE
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          globally_quoted_identifiers: true
      hibernate:
        ddl-auto: none
      show-sql: false
