server:
  port: 8888

spring:
  application:
    name: dqwapi
  jackson:
    serialization:
      indent_output: true

springdoc:
  swagger-ui:
    path: /api.html

dqwapi:
  version: $project.version
  kokoro-json: kokoro-min.json
  response: 20